services:
  unsdb:
    image: 'mongo'
    volumes:
      - unsdata:/data/db
    networks:
      - uns
  uns1:
    build: 
      context: ./uns
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - MONGO_HOST=unsdb
    ports:
      - '6968:80'
    depends_on:
      - unsdb
    networks:
      - uns
  uns2:
    build: 
      context: ./uns
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - MONGO_HOST=unsdb
    ports:
      - '6969:80'
    depends_on:
      - unsdb
    networks:
      - uns
  uns:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns1
      - uns2
    ports:
      - '6970:80'
    networks:
      - uns

  pmfdb:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pmf
  pmf:
    build:
      context: ./django-app
    environment:
      - DB_HOST=pmfdb
      - UNS_HOST=uns
      - FAKULTET=Prirodno matematicki fakultet
    ports:
      - '7010:8081'
    depends_on:
      pmfdb:
        condition: service_healthy
    networks:
      - uns
      - pmf

  ftndb:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ftn
  ftn:
    build:
      context: ./django-app
    environment:
      - DB_HOST=ftndb
      - UNS_HOST=uns
      - FAKULTET=Fakultet tehnickih nauka
    ports:
      - '7011:8081'
    depends_on:
      ftndb:
        condition: service_healthy
    networks:
      - uns
      - ftn

  pravnidb:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pravni
  pravni:
    build:
      context: ./django-app
    environment:
      - DB_HOST=pravnidb
      - UNS_HOST=uns
      - FAKULTET=Pravni fakultet
    ports:
      - '7012:8081'
    depends_on:
      pmfdb:
        condition: service_healthy
    networks:
      - uns
      - pravni
volumes:
  unsdata:
networks:
  uns:
  pmf:
  ftn:
  pravni: