services:
  unsdb:
    image: 'mongo'
    volumes:
      - unsdata:/data/db
    networks:
      - uns
  uns1:
    build: 
      context: ./uns
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - MONGO_HOST=unsdb
    ports:
      - '6968:80'
    depends_on:
      - unsdb
    networks:
      - uns
  uns2:
    build: 
      context: ./uns
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - MONGO_HOST=unsdb
    ports:
      - '6969:80'
    depends_on:
      - unsdb
    networks:
      - uns
  uns:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns1
      - uns2
    ports:
      - '6970:80'
    networks:
      - uns

  mysitedb:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mysite
  backend:
    build:
      context: ./django-app
    environment:
      - DB_HOST=mysitedb
      - UNS_HOST=uns
      - FAKULTET=Prirodno matematicki fakultet
    ports:
      - '6999:8081'
    depends_on:
      mysitedb:
        condition: service_healthy
    networks:
      - uns
      - mysite
volumes:
  unsdata:
networks:
  uns:
  mysite: